### ISSUE TITLE
Jackson Deserialisation Bug

### ISSUE THREAD

**Issue by vlad-ge** [springwolf/springwolf-core#114]
**Context**
Firstly, thanks a lot for the features of springwolf. Very nice work!

Remark: This is my first bug report, I hope I am doing it the "right" way. If not, any remarks in the right direction are welcomed!

**Describe the bug**
While trying to publish an kafka event through "springwolf-ui" a deserialisation error occurs at io.github.stavshamir.springwolf.asyncapi.dtos.KafkaMessageDto due to missing default constructor for jackson. 

**Dependencies and versions used**
`springwolf-kafka` version `0.9.0`.
`springwolf-ui` version `0.6.0`.

**Code example**

```
package io.github.stavshamir.springwolf.asyncapi.dtos;

import lombok.Data;
import lombok.extern.jackson.Jacksonized; --> Missing

import java.util.Map;

@Data
@Jacksonized --> Missing
public class KafkaMessageDto {

    private final Map<String, String> headers;

    private final Map<String, ?> payload;

}
```

**Stack trace and error logs**
```
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `io.github.stavshamir.springwolf.asyncapi.dtos.KafkaMessageDto` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (org.springframework.util.StreamUtils$NonClosingInputStream); line: 1, column: 2]
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67) ~[jackson-databind-2.13.4.jar:2.13.4]
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1904) ~[jackson-databind-2.13.4.jar:2.13.4]
	at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:400) ~[jackson-databind-2.13.4.jar:2.13.4]
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1349) ~[jackson-databind-2.13.4.jar:2.13.4]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1415) ~[jackson-databind-2.13.4.jar:2.13.4]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352) ~[jackson-databind-2.13.4.jar:2.13.4]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185) ~[jackson-databind-2.13.4.jar:2.13.4]
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323) ~[jackson-databind-2.13.4.jar:2.13.4]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674) ~[jackson-databind-2.13.4.jar:2.13.4]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3682) ~[jackson-databind-2.13.4.jar:2.13.4]
```

**Comment by stavshamir** [comment]
Thanks for reporting this. I have not faced this issue while testing before the release, I will look again

**Comment by timonback** [comment]
Fix is released as part of `springwolf-kafka:0.10.3`
@vlad-ge Are you able to update springwolf and confirm that this issue is fixed?

**Comment by timonback** [comment]
Closing due to inactivity

**Comment by gabryellr** [comment]
I think he had an issue to upload the jar @timonback  https://github.com/springwolf/springwolf-core/issues/625
