### ISSUE TITLE
Not create bean when exist publish and subscribed messages

### ISSUE THREAD

**Issue by stepanovD** [springwolf/springwolf-core#149]
**Describe the bug**
If I have subscribed messages I get exception

**Dependencies and versions used**
For example, `springwolf-kafka` version `0.10.0`.

**Code example**
```java
private static Operation mergeOperation(Operation operation, Operation otherOperation) {
        Set<Message> mergedMessages = getMessages(operation);
        Set<Message> currentEntryMessages = getMessages(otherOperation);

//here is problem because getMessages return TreeSet and Message is not Comparable. 
        mergedMessages.addAll(currentEntryMessages); 

        Operation mergedOperation = operation != null ? operation : otherOperation;
        if (!mergedMessages.isEmpty()) {
            mergedOperation.setMessage(toMessageObjectOrComposition(mergedMessages));
        }
        return mergedOperation;
    }

    private static Set<Message> getMessages(Operation operation) {
        return Optional
                .ofNullable(operation)
                .map(Operation::getMessage)
                .map(MessageHelper::messageObjectToSet)
                .orElseGet(TreeSet::new);
    }
```

**Stack trace and error logs**
Caused by: java.lang.ClassCastException: class io.github.stavshamir.springwolf.asyncapi.types.channel.operation.message.Message cannot be cast to class java.lang.Comparable (io.github.stavshamir.springwolf.asyncapi.types.channel.operation.message.Message is in unnamed module of loader 'app'; java.lang.Comparable is in module java.base of loader 'bootstrap')
	at java.base/java.util.TreeMap.compare(TreeMap.java:1569)
	at java.base/java.util.TreeMap.addEntryToEmptyMap(TreeMap.java:776)
	at java.base/java.util.TreeMap.put(TreeMap.java:785)
	at java.base/java.util.TreeMap.put(TreeMap.java:534)
	at java.base/java.util.TreeSet.add(TreeSet.java:255)
	at java.base/java.util.AbstractCollection.addAll(AbstractCollection.java:336)
	at java.base/java.util.TreeSet.addAll(TreeSet.java:309)
	at io.github.stavshamir.springwolf.asyncapi.scanners.channels.ChannelMerger.mergeOperation(ChannelMerger.java:47)

**Comment by timonback** [comment]
Hi @stepanovD, thank you for the report.

This sounds like the issue fixed in https://github.com/springwolf/springwolf-core/pull/137

Can you update springwolf-kafka to 0.10.3 and try again?

**Comment by timonback** [comment]
Closing due to inactivity.
