### ISSUE TITLE
Unable to get the springwolf-cloud-stream-example running

### ISSUE THREAD

**Issue by xadil** [springwolf/springwolf-core#171]
**Describe the bug**
Tried running the springwolf-cloud-stream-example after git download. It has an error and does not render the UI completely. I have similar issue with my own app after using the example.
It works if we downgrade the dependency runtimeOnly("io.github.springwolf:springwolf-ui:0.6.0")

**Dependencies and versions used**
io.github.springwolf:springwolf-ui:0.7.0

**Code example**

**Stack trace and error logs**
This is the error in the browser console.
`ERROR TypeError: Cannot read properties of undefined (reading 'kafka')
    at template (main.5ecc657c49ba83aa.js:1:506416)
    at Q_ (main.5ecc657c49ba83aa.js:1:57607)
    at Xa (main.5ecc657c49ba83aa.js:1:56398)
    at TI (main.5ecc657c49ba83aa.js:1:63236)
    at dI (main.5ecc657c49ba83aa.js:1:57258)
    at Xa (main.5ecc657c49ba83aa.js:1:57269)
    at AI (main.5ecc657c49ba83aa.js:1:56823)
    at Xa (main.5ecc657c49ba83aa.js:1:56848)
    at TI (main.5ecc657c49ba83aa.js:1:63236)
    at dI (main.5ecc657c49ba83aa.js:1:57258)`

**Comment by timonback** [comment]
Hi @xadil,
Thank you for raising this.

There is indeed a bug that the message binding field is not being rendered for the cloud stream plugin. The above PR will resolve it and will be part of the next release.
