### ISSUE TITLE
Failed to inject WebTestClient when using springwolf-core

### ISSUE THREAD

**Issue by Santiago-Rocha** [springwolf/springwolf-core#29]
Hi!
Amazing project

I build and reactive api with spring webflux and kafka, I have an issue when I implement springwolf-core to document kafka listeners and WebTestClient for my tests, the log is next

    Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.test.web.reactive.server.WebTestClient' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1777)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1333)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1287)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640)
	... 87 more

The error looks like a conflict with swagger-inflector
This is my test class

```kotlin
@SpringBootTest(classes = [TestConfiguration::class])
@ExtendWith(SpringExtension::class)
@AutoConfigureWebTestClient
class CrudControllerTest {
    @Autowired
    private lateinit var client: WebTestClient
    ...    
}
```

**Comment by stavshamir** [comment]
Thanks for opening the issue! 

A few questions that could help me solve this it:
1. Could you please share the entire stack trace?
2. Why do you think it's related to the inflector? 
3. What version of swagger do you use? If you can, please provide the exact Gradle/maven dependency for swagger.

**Comment by stavshamir** [comment]
Closed due to inactivity.
