### ISSUE TITLE
/springwolf/docs page -> 404

### ISSUE THREAD

**Issue by pdalfarr** [springwolf/springwolf-core#348]
**Describe the bug**
I am giving a try to [Springwolf][1] to generate the documentation of my RabbitMQ Spring back-end code, and I managed to display the http://localhost:8080/springwolf/asyncapi-ui.html page.

**1. Problem**

The http://localhost:8080/springwolf/asyncapi-ui.html page only shows this:

    Springwolf 
    
    API VERSION - AsyncAPI JSON file
    
    Servers
    Channels
    
    Semantics of publish and subscribe:
    
    publish  means publish an event to the channel and this application will receive it
    subscribe  means subscribe to this channel to receive events published by this application
    
    Schemas

whereas **it should display a full list of info similar to this page**: https://demo.springwolf.dev/springwolf-ui/asyncapi-ui.html 

**2. Investigation**

After investigating I noticed that the asyncapi-ui.html does an http request towards

    http://localhost:8080/springwolf/docs 

and this returns an "**HTTP Status 404 – Not Found**" ! 

It's as if this url was not handled by Springwolf. 

I read the documentation https://www.springwolf.dev/docs/configuration/ and tried to change the url of the docs (I know it does break the Springwolf HTML UI, but I am just investigating to understand what's going on).

So I set this in application.yml:

    springwolf:
      paths:
        docs: /springwolf/testdocs

and then I opened 

    http://localhost:8080/springwolf/testdocs

it does not work!<BR/>
Also, in application yml, IntelliJ does underline "docs:" and a popup say:

    cannot resolve configuration property 'springwolf.paths.docs' 

I now deleted this springwolf.paths.docs parameter, but I wonder why, when I set it , I have this popup. Did this parameter changed ?

**3. Questions**

 - How is that /springwolf-ui/asyncapi-ui.html page is displayed but /springwolf-ui/docs returns a 404.<BR/>**How can I fix this 404?**
 - Should I be worried about IntelliJ says "cannot resolve configuration property 'springwolf.paths.docs'" about "docs:' application yaml parameter?

Thanks beforehand for your help.

FYI: message also on SO: https://stackoverflow.com/questions/77066903/springwolf-http-localhost8080-springwolf-docs-page-404

  [1]: https://www.springwolf.dev/

**Dependencies and versions used**
```
		<dependency>
			<groupId>io.github.springwolf</groupId>
			<artifactId>springwolf-amqp</artifactId>
			<version>0.14.0</version>
		</dependency>
		<!-- Provides the UI - optional (recommended) -->
		<dependency>
			<groupId>io.github.springwolf</groupId>
			<artifactId>springwolf-ui</artifactId>
			<version>0.14.0</version>
		</dependency>
```

**Code example**
No code sample

**Stack trace and error logs**
no stack trace

**Comment by timonback** [comment]
Hi @pdalfarr,

the `/docs` endpoint is being served by a Spring controller, while `asyncapi-ui.html` is a static asset. So the controller is an overlay to the static assets.

I checked the `https://github.com/springwolf/springwolf-core/tree/master/springwolf-examples/springwolf-amqp-example` example project (docker-compose up. Current springwolf version in the `.env` file is 0.14.0) and the UI is rendered as expected. Maybe you find some differences to your code and/or dependencies.

For me it is difficult to analyze, without further details/code.
You can try to increase the logging via `logging.level.io.github.stavshamir.springwolf=DEBUG` and/or try to set a breakpoint in `AsyncApiController` and check if the request is arriving in the controller - spring security might block it.

We have a FAQ section, maybe it contains the solution already. If not, please report back so we can add it there: https://www.springwolf.dev/docs/faq#the-springwolf-ui-is-not-showing

**Comment by pdalfarr** [comment]
Thanks for your response.

After reading your code, I suspected that, somehow, some of your bean are not loaded.
So I forced component scan to include your package (I know, this should not be necessary, but still I gave a try it)

@ComponentScan(
        value = {"my.package", "io.github.stavshamir.springwolf"},

and now I see this:

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springwolfAmqpController': Lookup method resolution failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [io.github.stavshamir.springwolf.asyncapi.SpringwolfAmqpController] from ClassLoader [jdk.internal.loader.ClassLoaders$AppClassLoader@1d44bcfa]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:289) ~[spring-beans-5.3.16.jar:5.3.16]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineConstructorsFromBeanPostProcessors(AbstractAutowireCapableBeanFactory.java:1302) ~[spring-beans-5.3.16.jar:5.3.16]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1219) ~[spring-beans-5.3.16.jar:5.3.16]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.16.jar:5.3.16]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.16.jar:5.3.16]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.16.jar:5.3.16]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.16.jar:5.3.16]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.16.jar:5.3.16]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.16.jar:5.3.16]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953) ~[spring-beans-5.3.16.jar:5.3.16]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.16.jar:5.3.16]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.16.jar:5.3.16]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.6.4.jar:2.6.4]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:740) ~[spring-boot-2.6.4.jar:2.6.4]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:415) ~[spring-boot-2.6.4.jar:2.6.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) ~[spring-boot-2.6.4.jar:2.6.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1312) ~[spring-boot-2.6.4.jar:2.6.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301) ~[spring-boot-2.6.4.jar:2.6.4]
	at my.package.MyApplication.main(MyApplication.java:29) ~[classes/:na]
Caused by: java.lang.IllegalStateException: Failed to introspect Class [io.github.stavshamir.springwolf.asyncapi.SpringwolfAmqpController] from ClassLoader [jdk.internal.loader.ClassLoaders$AppClassLoader@1d44bcfa]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:485) ~[spring-core-5.3.16.jar:5.3.16]
	at org.springframework.util.ReflectionUtils.doWithLocalMethods(ReflectionUtils.java:321) ~[spring-core-5.3.16.jar:5.3.16]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:267) ~[spring-beans-5.3.16.jar:5.3.16]
	... 18 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/springframework/http/HttpStatusCode
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[na:na]
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[na:na]
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2504) ~[na:na]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:467) ~[spring-core-5.3.16.jar:5.3.16]
	... 20 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.http.HttpStatusCode
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[na:na]
	... 24 common frames omitted
```

So the explanation probably is that HttpStatusCode has been introduced in 6.0, but in my project I am using 5.3.16

```
https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/HttpStatusCode.html -> ok 
https://docs.spring.io/spring-framework/docs/5.3.16/javadoc-api/org/springframework/http/HttpStatusCode.html -> 404 Oops! The page can’t be found.

```
Do you think you can do something about that?

Also, maybe this is just the first error... 

Thanks for your help

Pascal

**Comment by timonback** [comment]
Thanks, that output helps.

As an open source project we have limited resources and therefore only support the latest version - which is Spring Boot 3 (implicitly including Spring Framework 6).

You could try an outdated springwolf version (https://www.springwolf.dev/docs/faq#is-spring-boot-2x-supported), but I recommend to update to the latest Spring version.

**Comment by pdalfarr** [comment]
I am using 

```
@RabbitListener(autoStartup = "false",
                queuesToDeclare = @Queue(name = "name", autoDelete = "false", durable = "true"),
                containerFactory = "factory",
                errorHandler = "errorHandler")

```

and I think your code ony check `bindings` an 'queues'

I guess you should also check `queuesToDeclare`, right?

**Comment by pdalfarr** [comment]
Hi,

So I managed to make your lib work with `my Spring 5.3.16 project` where I am using `queusToDeclare` :-)
 - I copied and slightly tweaked 2 mising classes: DefaultHttpStatusCode and HttpStatusCode) (wou don't need this in your library I guess)
 - I changed a bit RabbitListenerUtil.java (and created an PR bout that): for what is worth, I quickly create a PR about that so you can see the code changes: https://github.com/springwolf/springwolf-core/pull/352 
 
I don't know how to build my fork on github, but that's not an issue: my goal is just to share the code change with you ;-)

Thanks a lot for this great library :-)

**Comment by pdalfarr** [comment]
@timonback Can I kindly ask you if you had some time to look at my PR which does add support for queuesToDeclare?
If this could be added in a 0.14.1 version of  springwolf-amqp-plugin that would be great!
Thanks

**Comment by pdalfarr** [comment]
Hi @timonback 

I just added a test case in the PR: I hope it will be good enough.

And, by the way, thanks a lot for Springwolf: you did an amazing job 👍

**Comment by pdalfarr** [comment]
Hi @timonback

I had a hard time dealing with with 'IntelliJ auto-organize' , 'GithHub import requirements' and 'usage of gradlew :spotlessApply'...
It should be OK now (all tests are OK on my side), so I guess a build can be triggered again..

Sorry for the inconvenience.

Pascal

**Comment by sam0r040** [comment]
Build looks good now, I will have a look tomorrow...

**Comment by sam0r040** [comment]
Hi @pdalfarr, 
I did a small refactoring on your change so that we dont have to add commons-lang as a dependency. Everything else looked good and I therefore merged your PR. Thanks a lot for your contribution! 

Is there anything else to do/discuss in this issue or can we close it?

**Comment by pdalfarr** [comment]
Hi @sam0r040 ,

Thanks a lot for the review and code changes.
Good to see that the PR has been merged :-)

Nothing else on my side, so I think this issue can be closed.

Just on remark:
please do not enforce the use of Spring Boot 3 and Spring 6, so I am still able to use your library in my 'old' Spring Boot 2.7 project.
(I'll update my project to Spring Boot 3 in the future, but the time isn't right as we speak)

I am looking forward to test Springwolf 0.15 :-)

Pascal

**Comment by pdalfarr** [comment]
Hi @sam0r040 

I see this 'waiting for feedback' lable and I am not sure about the meaning of this.
Do you need more information from my side?

**Comment by sam0r040** [comment]
No we don't need more information, I just didn't update the status after your reply.
