### ISSUE TITLE
Spring annotations removed from some classes - problematic for 'old' Spring applications

### ISSUE THREAD

**Issue by pdalfarr** [springwolf/springwolf-core#478]
**Describe the bug**
Using SpringWolf 0.16.0, I encountered the following problem:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of constructor in io.github.stavshamir.springwolf.asyncapi.controller.AsyncApiController required a bean of type 'io.github.stavshamir.springwolf.asyncapi.AsyncApiService' that could not be found.


Action:

Consider defining a bean of type 'io.github.stavshamir.springwolf.asyncapi.AsyncApiService' in your configuration.

```

I found out that some annotations were removed:
cfr https://github.com/springwolf/springwolf-core/commit/c23bcf0d912355298681f004b3aef0e90168a5e9#diff-4662878ccf79273def53e3479ec98c2b1b06a28e42787377ca5fa7d3c3484615L18

This is problematic for users (like me) using an old version of Spring and Spring Boot (see below)
This problem is NOT present when using `springwolf 0.15.1`

**Dependencies and versions used**
`springwolf-core-0.16.0` ... with **Spring 5 and Spring Boot 2**

**Code example**
no code sample.

**Stack trace and error logs**
`
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'io.github.stavshamir.springwolf.asyncapi.AsyncApiService' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1799) ~[spring-beans-5.3.16.jar:5.3.16]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1355) ~[spring-beans-5.3.16.jar:5.3.16]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309) ~[spring-beans-5.3.16.jar:5.3.16]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887) ~[spring-beans-5.3.16.jar:5.3.16]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791) ~[spring-beans-5.3.16.jar:5.3.16]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229) ~[spring-beans-5.3.16.jar:5.3.16]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372) ~[spring-beans-5.3.16.jar:5.3.16]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222) ~[spring-beans-5.3.16.jar:5.3.16]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.16.jar:5.3.16]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.16.jar:5.3.16]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.16.jar:5.3.16]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.16.jar:5.3.16]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.16.jar:5.3.16]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.16.jar:5.3.16]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953) ~[spring-beans-5.3.16.jar:5.3.16]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.16.jar:5.3.16]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.16.jar:5.3.16]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.6.4.jar:2.6.4]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:740) ~[spring-boot-2.6.4.jar:2.6.4]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:415) ~[spring-boot-2.6.4.jar:2.6.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) ~[spring-boot-2.6.4.jar:2.6.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1312) ~[spring-boot-2.6.4.jar:2.6.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301) ~[spring-boot-2.6.4.jar:2.6.4]
	at be.opw.tourneecontrole.TourneeControleApplication.main(TourneeControleApplication.java:32) ~[classes/:na]
`

**Proposed solution**

If it's OK, please put back these annotations
Thanks

**Comment by timonback** [comment]
Hi @pdalfarr ,

Thank you for the report.

The commit you refer to makes use of Spring Boot Auto-configuration mechanism. It exists already in Spring Boot 2, although the use of the imports file was added later.

Can you try to '@Import' the auto configuration classes added in that commit?

As an open source project, we have limited resources and decided to only support the current Spring Boot version (3).

**Comment by pdalfarr** [comment]
Hi @timonback 

You are right:

`@Import({
        SpringwolfAutoConfiguration.class,
        SpringwolfAmqpAutoConfiguration.class,
})
`
does the job: thanks a lot!

As far as I am concerned, we can close this ticket.
