### ISSUE TITLE
KafkaListener method without any argument throw exception

### ISSUE THREAD

**Issue by alievrenkut** [springwolf/springwolf-core#665]
**Describe the bug**
Springwolf throws exception at below if project has a method without any argument. 
`java.lang.IllegalArgumentException: Payload cannot be detected. Method must not have 0 parameters`

I think zero argument method should be ok and should supported by springwolf.

**Dependencies and versions used**
`springwolf-kafka` version `1.0.0`.

**Code example**
```java
    @KafkaListener(topics = KafkaTopics.Context.END_MISSION_TOPIC, containerFactory = "protobufKafkaListenerContainerFactory")
    public void endMission() {

    }
```

**Stack trace and error logs**
java.lang.IllegalArgumentException: Payload cannot be detected. Method must not have 0 parameters: MissionManagmentKafkaService::endMission
	at io.github.springwolf.core.asyncapi.scanners.common.payload.PayloadClassExtractor.getPayloadParameterIndex(PayloadClassExtractor.java:45)
	at io.github.springwolf.core.asyncapi.scanners.common.payload.PayloadClassExtractor.extractFrom(PayloadClassExtractor.java:33)
	at io.github.springwolf.core.asyncapi.scanners.operations.annotations.SpringAnnotationMethodLevelOperationsScanner.mapMethodToOperation(SpringAnnotationMethodLevelOperationsScanner.java:62)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1715)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at io.github.springwolf.core.asyncapi.scanners.operations.SpringAnnotationOperationsScanner.mapToOperations(SpringAnnotationOperationsScanner.java:31)
	at io.github.springwolf.core.asyncapi.scanners.operations.SpringAnnotationOperationsScanner.scan(SpringAnnotationOperationsScanner.java:25)
	at io.github.springwolf.core.asyncapi.operations.DefaultOperationsService.findOperations(DefaultOperationsService.java:34)
	at io.github.springwolf.core.asyncapi.DefaultAsyncApiService.initAsyncAPI(DefaultAsyncApiService.java:71)
	at io.github.springwolf.core.asyncapi.DefaultAsyncApiService.getAsyncAPI(DefaultAsyncApiService.java:42)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by timonback** [comment]
Hi @alievrenkut 
Thank you for the report.

At this point we always expect at least one parameter as that is being used for the documentation of the payload.

In your example, is there no payload and the event just triggers some action?

**Comment by alievrenkut** [comment]
Hi @timonback 

Yes, we end current mission if we got any message we do not need any payload in this example. Currently I need to add a unused argument to make springwolf to work but then IDE does not like unsued argument :-(

**Comment by timonback** [comment]
I see, it is a trigger endpoint/consumer.

At the moment, we require the message so that users know that no payload (of none or multiple parameters) was be detected.
I assume, you use the kafkalistener annotation and no combination with the asynclistener annotation.

I wonder whether the exception should be turned into a log with log level warn. And the 'detected' default payload would be a plain object?
