### ISSUE TITLE
Cannot use @Header annotation with method parameters. UnsupportedOperationException: SchemaObjectMerger.merge is trying to put on immutable properties map.

### ISSUE THREAD

**Issue by Host32** [springwolf/springwolf-core#938]
**Describe the bug**
When I add a parameter annotated with `org.springframework.messaging.handler.annotation.@Header` in the listener method, the application fails to start

**Dependencies and versions used**
- springwolf-jms:1.5.0
- org.springframework.boot:3.3.1
- Java 21

**Code example**
```Java
@JmsListener(destination = MessageAddresses.DataChange.SERVER_ADDRESS)
public void onDataChange(@Header("entityClass") String entityClass, @Payload EntityChangedMessage body) {
    log.info("Received DataChange Event: {}", body);
}
```

**Stack trace and error logs**
```
DefaultOperationsService] An error was encountered during operation scanning with io.github.springwolf.core.asyncapi.scanners.operations.SpringAnnotationOperationsScanner@55f13960: null
java.lang.UnsupportedOperationException: null
	at java.base/java.util.ImmutableCollections.uoe(ImmutableCollections.java:142)
	at java.base/java.util.ImmutableCollections$AbstractImmutableMap.putIfAbsent(ImmutableCollections.java:1081)
	at io.github.springwolf.core.asyncapi.schemas.SchemaObjectMerger.lambda$merge$0(SchemaObjectMerger.java:14)
	at java.base/java.util.HashMap.forEach(HashMap.java:1429)
	at io.github.springwolf.core.asyncapi.schemas.SchemaObjectMerger.merge(SchemaObjectMerger.java:14)
	at io.github.springwolf.core.asyncapi.scanners.common.MethodLevelAnnotationScanner.buildMessage(MethodLevelAnnotationScanner.java:34)
	at io.github.springwolf.core.asyncapi.scanners.operations.annotations.SpringAnnotationMethodLevelOperationsScanner.buildOperation(SpringAnnotationMethodLevelOperationsScanner.java:87)
	at io.github.springwolf.core.asyncapi.scanners.operations.annotations.SpringAnnotationMethodLevelOperationsScanner.mapMethodToOperation(SpringAnnotationMethodLevelOperationsScanner.java:80)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1715)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at io.github.springwolf.core.asyncapi.scanners.operations.SpringAnnotationOperationsScanner.mapToOperations(SpringAnnotationOperationsScanner.java:31)
	at io.github.springwolf.core.asyncapi.scanners.operations.SpringAnnotationOperationsScanner.scan(SpringAnnotationOperationsScanner.java:25)
	at io.github.springwolf.core.asyncapi.operations.DefaultOperationsService.findOperations(DefaultOperationsService.java:34)
	at io.github.springwolf.core.asyncapi.DefaultAsyncApiService.initAsyncAPI(DefaultAsyncApiService.java:71)
	at io.github.springwolf.core.asyncapi.DefaultAsyncApiService.getAsyncAPI(DefaultAsyncApiService.java:42)
	at io.github.springwolf.core.SpringwolfInitApplicationListener.onApplicationEvent(SpringwolfInitApplicationListener.java:31)
	at io.github.springwolf.core.SpringwolfInitApplicationListener.onApplicationEvent(SpringwolfInitApplicationListener.java:17)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:185)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:178)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:156)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:451)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:384)
	at org.springframework.boot.context.event.EventPublishingRunListener.ready(EventPublishingRunListener.java:109)
	at org.springframework.boot.SpringApplicationRunListeners.lambda$ready$6(SpringApplicationRunListeners.java:80)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:118)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:112)
	at org.springframework.boot.SpringApplicationRunListeners.ready(SpringApplicationRunListeners.java:80)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:349)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1363)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1352)
	at org.example.MyApplication.main(MyApplication.java:25)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:50)
```

**Comment by Host32** [comment]
I found a solution by changing the order of the arguments, if I put the Payload first it works:
```java
@JmsListener(destination = MessageAddresses.DataChange.SERVER_ADDRESS)
public void onDataChange(@Payload EntityChangedMessage body, @Header("entityClass") String entityClass) {
    log.info("Received DataChange Event: {}", body);
}
```

I didn't find this specification in the documentation, despite this the problem can be worked around.

**Comment by timonback** [comment]
Hi @Host32 ,
Thank you for the report and surprising workaround.

The mentioned `SchemaObjectMerger` is a class by Springwolf, so I suspect a bug involving an `ImmutableMap` lurking there.

Feel free to investigate and/or update the jms example so that this case is covered by (integration) tests.

**Comment by Host32** [comment]
After further investigation, I found out that the problem occurs because `SpringwolfJmsScannerConfiguration.java` uses `AsyncHeadersNotDocumented` by default to build header documentation.

I solved the problem definitively by creating a custom `AsyncHeadersBuilder` and overriding the `SpringAnnotationChannelsScanner` and `SpringAnnotationOperationsScanner` beans configuration to use my customization:

```java
@Configuration
public class AsyncApiConfiguration {
    @Bean
    @Primary
    public SpringAnnotationChannelsScanner jmsMethodLevelListenerAnnotationChannelsScanner(
            SpringwolfClassScanner springwolfClassScanner, JmsBindingFactory jmsBindingFactory,
            PayloadMethodParameterService payloadMethodParameterService, HeaderClassExtractor headerClassExtractor,
            ComponentsService componentsService) {
        SpringAnnotationMethodLevelChannelsScanner<JmsListener> strategy =
                new SpringAnnotationMethodLevelChannelsScanner<>(JmsListener.class, jmsBindingFactory,
                        new AsyncHeadersForJmsBuilder(), payloadMethodParameterService, headerClassExtractor,
                        componentsService);

        return new SpringAnnotationChannelsScanner(springwolfClassScanner, strategy);
    }

    @Bean
    @Primary
    public SpringAnnotationOperationsScanner jmsMethodLevelListenerAnnotationOperationsScanner(
            SpringwolfClassScanner springwolfClassScanner, JmsBindingFactory jmsBindingFactory,
            PayloadMethodParameterService payloadMethodParameterService, HeaderClassExtractor headerClassExtractor,
            ComponentsService componentsService) {
        SpringAnnotationMethodLevelOperationsScanner<JmsListener> strategy =
                new SpringAnnotationMethodLevelOperationsScanner<>(JmsListener.class, jmsBindingFactory,
                        new AsyncHeadersForJmsBuilder(), List.of(), payloadMethodParameterService, headerClassExtractor,
                        componentsService);

        return new SpringAnnotationOperationsScanner(springwolfClassScanner, strategy);
    }
}

public class AsyncHeadersForJmsBuilder implements AsyncHeadersBuilder {
    @Override
    public SchemaObject buildHeaders(NamedSchemaObject payloadSchema) {
        return SchemaObject.builder().type("object").title(payloadSchema.title() + "-Headers")
                .properties(new HashMap<>()).build();
    }
}
```

**Comment by timonback** [comment]
Hi @Host32,
we looked into it and discovered that in these cases, the existing header schema should not be modified at all. Instead, a new header schema should be created - to avoid polluting the schema used by other operations.

Feel free to test the SNAPSHOT version. The workaround you provided should not be needed anymore.
